language: c

sudo: required

compiler:
  - gcc
  - clang

script:
  - ./configure -prefix=/usr --sysconfdir=/etc --enable-eap-gtc --enable-xauth-pam --enable-unity && make && make install

before_install:
  - sudo apt-get update
  - sudo apt-get install libgmp3-dev
  - sudo apt-get install libpam0g-dev

